services:
  apigateway:
    container_name: rampnow-api-gateway
    image: rampnow-api-gateway
    build:
      context: ./rampnow-api-gateway
    depends_on:
      - postgres
    ports:
      - 3005:3005
  authsvc:
    container_name: rampnow-auth-svc
    image: rampnow-auth-svc
    build:
      context: ./rampnow-auth-svc
    depends_on:
      - postgres
    ports:
      - 50056:50056
  paymentsvc:
    container_name: rampnow-payment-svc
    image: rampnow-payment-svc
    build:
      context: ./rampnow-payment-svc
    depends_on:
      - postgres
    ports:
      - 50057:50057
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rampnowdb
    ports:
      - 5433:5432

volumes:
  db-data:
