version: '3'
services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Sethukumar@123
      MYSQL_DATABASE: order_svc
      MYSQL_USER: mysql
      MYSQL_PASSWORD: Sethukumar@123
    ports: 
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - myapp

  api:
    build: . 
    image: sethukumarj/order_svc
    env_file:
      - .env
    ports: 
      - 50057:50057
    restart: on-failure
    depends_on:
      - mysql
    networks:
      - myapp

volumes:
  db:

networks:
  myapp:

