version: '3'
services:

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=test
      - DATABASE_HOST=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - myapp

  api:
    build: . 
    image: sethukumarj/auth_svc
    env_file:
      - .env
    ports: 
      - 50056:50056
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - myapp
volumes:
  db:
networks:
  myapp: